name: Release

on:
  push:
    branches:
      - master

jobs:
  u-project-1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "12"
      - run: npm install
      - run: npm run test:unit
      - name: Publish
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=site --functions=functions
        env:
          NETLIFY_SITE_ID: "579b264c-d71b-4329-91d4-ef2060b90cdd"
          NETLIFY_AUTH_TOKEN: "c2db1f663abfb4afb770a26366ce1893ce2724571101932e72cbdcbb8995bc1c"
